### PR TITLE
fix(object-cache): improve reliability of object cache management

### LINKED ISSUE #502: [Bug]: WAL archival fails in v0.6.0 if ObjectStore and credentials Secret have the same name
Hello folks,

Upon upgrading from of the plugin from 0.5 to 0.6 I am seeing cache related errors, and WAL archiving stops functioning.

```
{"level":"info","ts":"2025-08-29T11:26:40.37474019Z","msg":"Restoring WAL file","logging_pod":"obfuscated-db-stage-3","objectStore":"obfuscated-db-stage-backup","serverName":"obfuscated-db-stage","walName":"0000000100000003000000CF"}
{"level":"error","ts":"2025-08-29T11:26:40.374786516Z","msg":"Error while handling GRPC request","logging_pod":"obfuscated-db-stage-3","info":{"Server":{"Client":{"Client":{}},"InstanceName":"obfuscated-db-stage-3","SpoolDirectory":"/controller/wal-restore-spool","PGDataPath":"/var/lib/postgresql/data/pgdata","PGWALPath":"/var/lib/postgresql/data/pgdata/pg_wal"},"FullMethod":"/cnpgi.wal.v1.WAL/Restore"},"error":"while getting recover credentials: while getting secret obfuscated-db-stage-backup: cache had type *v1.ObjectStore, but *v1.Secret was asked for"}
```

Formatted stacktrace: 
```
Stacktrace:
  1. github.com/cloudnative-pg/machinery/pkg/log.(*logger).Error
     (…/machinery@v0.3.1/pkg/log/log.go:125)
  2. github.com/cloudnative-pg/cnpg-i-machinery/pkg/pluginhelper/http.(*Server).Start.logFailedRequestsUnaryServerInterceptor.func2
     (…/cnpg-i-machinery@v0.4.0/pkg/pluginhelper/http/grpc.go:51)
  3. google.golang.org/grpc.NewServer.chainUnaryServerInterceptors.chainUnaryInterceptors.func1
     (…/grpc@v1.75.0/server.go:1234)
  4. github.com/cloudnative-pg/cnpg-i/pkg/wal._WAL_Restore_Handler
     (…/cnpg-i@v0.3.0/pkg/wal/wal_grpc.pb.go:214)
  5. google.golang.org/grpc.(*Server).processUnaryRPC
     (…/grpc@v1.75.0/server.go:1431)
  6. google.golang.org/grpc.(*Server).handleStream
     (…/grpc@v1.75.0/server.go:1842)
  7. google.golang.org/grpc.(*Server).serveStreams.func2.1
     (…/grpc@v1.75.0/server.go:1061)
<RequestAccomplished>1
```
Cluster and ObjectStore CR:

```
apiVersion: v1
items:
- apiVersion: postgresql.cnpg.io/v1
  kind: Cluster
  metadata:
    annotations:
      meta.helm.sh/release-name: obfuscated-db-stage
      meta.helm.sh/release-namespace: obfuscated-apiserver-stage
    creationTimestamp: "2025-08-25T14:23:01Z"
    generation: 3
    labels:
      app.kubernetes.io/instance: obfuscated-db-stage
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: obfuscated-db
      app.kubernetes.io/version: 1.16.0
      helm.sh/chart: obfuscated-db-0.1.0
    name: obfuscated-db-stage
    namespace: obfuscated-apiserver-stage
    resourceVersion: "71501546"
    uid: ce32f2c5-8ddd-4ee6-b140-6273b1b151af
  spec:
    affinity:
      nodeSelector:
        node-role.kubernetes.io/postgres: "true"
      podAntiAffinityType: preferred
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/postgres
        operator: Exists
    bootstrap:
      initdb:
        database: obfuscated
        encoding: UTF8
        import:
          databases:
          - obfuscated
          pgDumpExtraOptions:
          - --exclude-extension=pg_stat_kcache
          - --exclude-extension=set_user
          - --exclude-extension=pg_stat_statements
          pgRestoreExtraOptions:
          - --exclude-schema=metric_helpers
          - --exclude-schema=user_management
          schemaOnly: true
          source:
            externalCluster: obfuscated-db-stage-pgo
          type: microservice
        localeCType: C
        localeCollate: C
        owner: obfuscated
        postInitApplicationSQL:
        - CREATE EXTENSION IF NOT EXISTS pgcrypto WITH VERSION '1.3';
        - CREATE EXTENSION IF NOT EXISTS pg_trgm WITH VERSION '1.6';
        - GRANT ALL PRIVILEGES ON DATABASE obfuscated TO obfuscated;
        secret:
          name: obfuscated-db-stage-user
    description: Database for obfuscated
    enablePDB: true
    enableSuperuserAccess: true
    externalClusters:
    - connectionParameters:
        dbname: obfuscated
        host: obfuscated-db-stage-pgo.obfuscated.svc.int.nrk.cloud
        user: obfuscated
      name: obfuscated-db-stage-pgo
      password:
        key: password
        name: obfuscated-db-stage-import
    failoverDelay: 0
    imageName: ghcr.io/cloudnative-pg/postgresql:17.4
    instances: 3
    logLevel: info
    managed:
      services:
        additional:
        - selectorType: rw
          serviceTemplate:
            metadata:
              name: obfuscated-db-stage-rw-ext
            spec:
              type: LoadBalancer
          updateStrategy: patch
    maxSyncReplicas: 0
    minSyncReplicas: 0
    monitoring:
      customQueriesConfigMap:
      - key: queries
        name: cnpg-default-monitoring
      disableDefaultQueries: false
      enablePodMonitor: true
    plugins:
    - enabled: true
      isWALArchiver: true
      name: barman-cloud.cloudnative-pg.io
      parameters:
        barmanObjectName: obfuscated-db-stage-backup
    postgresGID: 26
    postgresUID: 26
    postgresql:
      parameters:
        archive_mode: "on"
        archive_timeout: 5min
        dynamic_shared_memory_type: posix
        full_page_writes: "on"
        log_destination: csvlog
        log_directory: /controller/log
        log_filename: postgres
        log_rotation_age: "0"
        log_rotation_size: "0"
        log_truncate_on_rotation: "false"
        logging_collector: "on"
        max_connections: "350"
        max_parallel_workers: "32"
        max_replication_slots: "32"
        max_slot_wal_keep_size: 25GB
        max_worker_processes: "32"
        random_page_cost: "1.2"
        seq_page_cost: "1"
        shared_memory_type: mmap
        shared_preload_libraries: ""
        ssl_max_protocol_version: TLSv1.3
        ssl_min_protocol_version: TLSv1.3
        wal_keep_size: 512MB
        wal_level: logical
        wal_log_hints: "on"
        wal_receiver_timeout: 5s
        wal_sender_timeout: 5s
      syncReplicaElectionConstraint:
        enabled: false
    primaryUpdateMethod: restart
    primaryUpdateStrategy: unsupervised
    probes:
      liveness:
        isolationCheck:
          connectionTimeout: 1000
          enabled: true
          requestTimeout: 1000
    replicationSlots:
      highAvailability:
        enabled: true
        slotPrefix: _cnpg_
      synchronizeReplicas:
        enabled: true
      updateInterval: 30
    resources:
      limits:
        cpu: "4"
        memory: 16Gi
      requests:
        cpu: 3500m
        memory: 14Gi
    smartShutdownTimeout: 180
    startDelay: 3600
    stopDelay: 1800
    storage:
      resizeInUseVolumes: true
      size: 100Gi
      storageClass: local-path
    superuserSecret:
      name: obfuscated-db-stage-admin
    switchoverDelay: 3600
  status:
    availableArchitectures:
    - goArch: amd64
      hash: 433bae32a2e3e459a2a181d67ed2b0dfcf67f359480b9646bbdc8ad8e2dd4ef1
    - goArch: arm64
      hash: 981f8452ecf423a37802c14018b7a73bfd25c1c2e82ec19de9c85cd54912adb7
    certificates:
      clientCASecret: obfuscated-db-stage-ca
      expirations:
        obfuscated-db-stage-ca: 2025-11-23 14:18:01 +0000 UTC
        obfuscated-db-stage-replication: 2025-11-23 14:18:01 +0000 UTC
        obfuscated-db-stage-server: 2025-11-23 14:18:01 +0000 UTC
      replicationTLSSecret: obfuscated-db-stage-replication
      serverAltDNSNames:
      - obfuscated-db-stage-rw
      - obfuscated-db-stage-rw.obfuscated-apiserver-stage
      - obfuscated-db-stage-rw.obfuscated-apiserver-stage.svc
      - obfuscated-db-stage-rw.obfuscated-apiserver-stage.svc.cluster.local
      - obfuscated-db-stage-r
      - obfuscated-db-stage-r.obfuscated-apiserver-stage
      - obfuscated-db-stage-r.obfuscated-apiserver-stage.svc
      - obfuscated-db-stage-r.obfuscated-apiserver-stage.svc.cluster.local
      - obfuscated-db-stage-ro
      - obfuscated-db-stage-ro.obfuscated-apiserver-stage
      - obfuscated-db-stage-ro.obfuscated-apiserver-stage.svc
      - obfuscated-db-stage-ro.obfuscated-apiserver-stage.svc.cluster.local
      - obfuscated-db-stage-rw-ext
      - obfuscated-db-stage-rw-ext.obfuscated-apiserver-stage
      - obfuscated-db-stage-rw-ext.obfuscated-apiserver-stage.svc
      - obfuscated-db-stage-rw-ext.obfuscated-apiserver-stage.svc.cluster.local
      serverCASecret: obfuscated-db-stage-ca
      serverTLSSecret: obfuscated-db-stage-server
    cloudNativePGCommitHash: 8b442dcc3
    cloudNativePGOperatorHash: 433bae32a2e3e459a2a181d67ed2b0dfcf67f359480b9646bbdc8ad8e2dd4ef1
    conditions:
    - lastTransitionTime: "2025-08-25T14:23:23Z"
      message: A single, unique system ID was found across reporting instances.
      reason: Unique
      status: "True"
      type: ConsistentSystemID
    - lastTransitionTime: "2025-08-29T11:26:39Z"
      message: Cluster is Ready
      reason: ClusterIsReady
      status: "True"
      type: Ready
    - lastTransitionTime: "2025-08-29T11:31:30Z"
      message: 'rpc error: code = Unknown desc = while getting secret obfuscated-db-stage-backup:
        cache had type *v1.ObjectStore, but *v1.Secret was asked for'
      reason: ContinuousArchivingFailing
      status: "False"
      type: ContinuousArchiving
    - lastTransitionTime: "2025-08-29T12:03:03Z"
      message: 'rpc error: code = Unknown desc = while getting secret obfuscated-db-stage-backup:
        cache had type *v1.ObjectStore, but *v1.Secret was asked for'
      reason: LastBackupFailed
      status: "False"
      type: LastBackupSucceeded
    configMapResourceVersion:
      metrics:
        cnpg-default-monitoring: "68207610"
    currentPrimary: obfuscated-db-stage-1
    currentPrimaryTimestamp: "2025-08-25T14:23:23.026731Z"
    healthyPVC:
    - obfuscated-db-stage-1
    - obfuscated-db-stage-2
    - obfuscated-db-stage-3
    image: ghcr.io/cloudnative-pg/postgresql:17.4
    instanceNames:
    - obfuscated-db-stage-1
    - obfuscated-db-stage-2
    - obfuscated-db-stage-3
    instances: 3
    instancesReportedState:
      obfuscated-db-stage-1:
        ip: 10.42.76.233
        isPrimary: true
        timeLineID: 1
      obfuscated-db-stage-2:
        ip: 10.42.79.33
        isPrimary: false
        timeLineID: 1
      obfuscated-db-stage-3:
        ip: 10.42.132.23
        isPrimary: false
        timeLineID: 1
    instancesStatus:
      healthy:
      - obfuscated-db-stage-1
      - obfuscated-db-stage-2
      - obfuscated-db-stage-3
    lastFailedBackup: "2025-08-29T12:03:03Z"
    latestGeneratedNode: 3
    managedRolesStatus: {}
    pgDataImageInfo:
      image: ghcr.io/cloudnative-pg/postgresql:17.4
      majorVersion: 17
    phase: Cluster in healthy state
    pluginStatus:
    - capabilities:
      - TYPE_RECONCILER_HOOKS
      - TYPE_LIFECYCLE_SERVICE
      name: barman-cloud.cloudnative-pg.io
      version: 0.6.0
    poolerIntegrations:
      pgBouncerIntegration: {}
    pvcCount: 3
    readService: obfuscated-db-stage-r
    readyInstances: 3
    secretsResourceVersion:
      applicationSecretVersion: "68207547"
      clientCaSecretVersion: "68207554"
      externalClusterSecretVersion:
        obfuscated-db-stage-import: "68207545"
      replicationSecretVersion: "68207556"
      serverCaSecretVersion: "68207554"
      serverSecretVersion: "68207555"
      superuserSecretVersion: "68207548"
    switchReplicaClusterStatus: {}
    systemID: "7542528595016773653"
    targetPrimary: obfuscated-db-stage-1
    targetPrimaryTimestamp: "2025-08-25T14:23:01.900319Z"
    timelineID: 1
    topology:
      instances:
        obfuscated-db-stage-1: {}
        obfuscated-db-stage-2: {}
        obfuscated-db-stage-3: {}
      nodesUsed: 3
      successfullyExtracted: true
    writeService: obfuscated-db-stage-rw
- apiVersion: barmancloud.cnpg.io/v1
  kind: ObjectStore
  metadata:
    annotations:
      meta.helm.sh/release-name: obfuscated-db-stage
      meta.helm.sh/release-namespace: obfuscated-apiserver-stage
    creationTimestamp: "2025-08-25T14:23:01Z"
    generation: 5
    labels:
      app.kubernetes.io/managed-by: Helm
    name: obfuscated-db-stage-backup
    namespace: obfuscated-apiserver-stage
    resourceVersion: "71475638"
    uid: 141bf226-5f5e-452d-bb8d-d7e6b9003c28
  spec:
    configuration:
      destinationPath: s3://obfuscated-dbbackup/rancher-nonprod/
      endpointCA:
        key: nrk-ca.pem
        name: obfuscated-db-stage-nrk-ca
      endpointURL: https://maecs.felles.ds.nrk.no
      s3Credentials:
        accessKeyId:
          key: username
          name: obfuscated-db-stage-backup
        secretAccessKey:
          key: password
          name: obfuscated-db-stage-backup
      wal:
        compression: bzip2
    instanceSidecarConfiguration:
      env:
      - name: AWS_REQUEST_CHECKSUM_CALCULATION
        value: when_required
      - name: AWS_RESPONSE_CHECKSUM_VALIDATION
        value: when_required
      retentionPolicyIntervalSeconds: 1800
    retentionPolicy: 7d
  status:
    serverRecoveryWindow:
      obfuscated-db-stage:
        firstRecoverabilityPoint: "2025-08-26T11:18:45Z"
        lastSuccussfulBackupTime: "2025-08-29T11:04:05Z"
kind: List
metadata:
  resourceVersion: ""
```

Let me know if you need any additional information.

### PR DESCRIPTION
**Pull request by mnencia**
This patch addresses several critical bugs in the object cache logic.

First, it resolves a regression introduced in version 0.6.0, where WAL archival would fail if an ObjectStore and its corresponding credentials Secret had the same name. This issue caused the cache to return an object of the wrong type, leading to errors such as “cache had type *v1.ObjectStore, but *v1.Secret was asked for.” As a result, archival and backup operations were halted after the upgrade (see #502).

Second, the patch corrects the cache expiration logic. Previously, cached objects expired after only one second, which led to unnecessary reloads.

Third, there was a flaw in the function designed to remove objects from the cache. This bug prevented objects from being removed as intended.

Closes #502

### CODE REVIEW

File: internal/cnpgi/instance/internal/client/client.go [hunk 1]
```diff
@@ -143,7 +143,7 @@ func (e *ExtendedClient) removeObject(object client.Object) {
 	for i, cache := range e.cachedObjects {
 		if cache.entry.GetNamespace() == object.GetNamespace() &&
 			cache.entry.GetName() == object.GetName() &&
-			cache.entry.GetObjectKind().GroupVersionKind() != object.GetObjectKind().GroupVersionKind() {
+			reflect.TypeOf(cache.entry) == reflect.TypeOf(object) {
```
Comment (mnencia) [inline internal/cnpgi/instance/internal/client/client.go:146]: The GVK is empty most of the time. This is the main reason for the buggy behaviour.

File: internal/cnpgi/instance/internal/client/client.go [hunk 2]
```diff
@@ -91,7 +90,7 @@ func (e *ExtendedClient) getCachedObject(
 		if cacheEntry.entry.GetNamespace() != key.Namespace || cacheEntry.entry.GetName() != key.Name {
 			continue
 		}
-		if cacheEntry.entry.GetObjectKind().GroupVersionKind() != obj.GetObjectKind().GroupVersionKind() {
+		if reflect.TypeOf(cacheEntry.entry) != reflect.TypeOf(obj) {
```
Comment (mnencia) [inline internal/cnpgi/instance/internal/client/client.go:93]: The GVK is empty most of the time. This is the main reason for the buggy behaviour.

**Review by armru — DISMISSED** [review]

**Review by armru — APPROVED** [review]

**Review by leonardoce — APPROVED** [review]
